name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
      env:
        MY_SECRET: ${{ secrets.CONNECT_WEBSOCKET }}
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Check Secret
      run: |
        if [ -z "$MY_SECRET" ]; then
          echo "Secret is not set"
        else
          echo "Secret is set"
        fi
